version: '3.3'
services:
    node-exporter:
        network_mode: host
        pid: host
        volumes:
            - '/:/host:ro,rslave'
        image: 'quay.io/prometheus/node-exporter:latest'

    prometheus:
        container_name: prometheus
        ports:
            - '9091:9090' #modify 9091 to your setup needs
        volumes:
            - '/srv/dev-disk-by-uuid-174fa174-a675-40ef-af9d-28f1578a19bb/Containers/Prometheus/prometheus.yaml:/config/prometheus.yaml' #modify the path for your install location
        image: prom/prometheus

    grafana:
        container_name: grafana
        ports:
            - '3457:3000' #modify 3457 to your setup needs
        image: grafana/grafana
